version: '3'
services:
    server:
        build: ./server
        container_name: server
    proxy-nginx:
        build: .
        container_name: proxy
        ports:
            - 80:8080
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf